### ISSUE TITLE
Processing Port?

### ISSUE THREAD

**Issue by softpunch** [fdb/frequensea#14]
Is there any possibility of porting this project [or parts of it] into a Processing library?
Would any of Frequensea's features be able to run in a Processing environment?

It's a fantastic application!

**Comment by fdb** [comment]
Frequensea is a pure C application with a Lua frontend. Porting it to Processing would mean changing the language, graphics layer, and scripting layer. In other words,  it would be an entirely different application by the time I'm finished.

The reason it was created in C was so it could benefit from integration with libraries (hackrf / librtl-sdr / Oculus) and speed. Porting it to Processing would lose that benefit.

So I don't have any interest at the moment of porting it to Processing. Is somebody else is willing to take up this challenge I would gladly assist where I can.

**Comment by softpunch** [comment]
Fair enough! I appreciate the thorough explanation!

I haven't yet made the jump into working with C, 
but I will certainly keep Frequensea in mind when I do.
