### ISSUE TITLE
Get the following build errors on ubuntu 14.10

### ISSUE THREAD

**Issue by testsdr** [fdb/frequensea#5]
ubuntu@ubuntu:~/frequensea/build$ make
[ 74%] Built target lua
[ 76%] Building C object CMakeFiles/frequensea.dir/src/nosc.c.o
/home/ubuntu/frequensea/src/nosc.c:50:6: error: #error Either __BIG_ENDIAN__ or __LITTLE_ENDIAN__ must be defined.
     #error Either __BIG_ENDIAN__ or __LITTLE_ENDIAN__ must be defined.
      ^
/home/ubuntu/frequensea/src/nosc.c: In function ‘parse_int32’:
/home/ubuntu/frequensea/src/nosc.c:114:5: error: implicit declaration of function ‘swap32’ [-Werror=implicit-function-declaration]
     swap32(p->pos);
     ^
/home/ubuntu/frequensea/src/nosc.c: In function ‘_nosc_server_start’:
/home/ubuntu/frequensea/src/nosc.c:226:21: error: storage size of ‘hints’ isn’t known
     struct addrinfo hints;
                     ^
/home/ubuntu/frequensea/src/nosc.c:231:22: error: ‘AI_PASSIVE’ undeclared (first use in this function)
     hints.ai_flags = AI_PASSIVE | AI_ADDRCONFIG;
                      ^
/home/ubuntu/frequensea/src/nosc.c:231:22: note: each undeclared identifier is reported only once for each function it appears in
/home/ubuntu/frequensea/src/nosc.c:231:35: error: ‘AI_ADDRCONFIG’ undeclared (first use in this function)
     hints.ai_flags = AI_PASSIVE | AI_ADDRCONFIG;
                                   ^
/home/ubuntu/frequensea/src/nosc.c:233:5: error: implicit declaration of function ‘getaddrinfo’ [-Werror=implicit-function-declaration]
     int err = getaddrinfo(hostname, port_name, &hints, &res);
     ^
/home/ubuntu/frequensea/src/nosc.c:239:24: error: dereferencing pointer to incomplete type
     int fd = socket(res->ai_family, res->ai_socktype, res->ai_protocol);
                        ^
/home/ubuntu/frequensea/src/nosc.c:239:40: error: dereferencing pointer to incomplete type
     int fd = socket(res->ai_family, res->ai_socktype, res->ai_protocol);
                                        ^
/home/ubuntu/frequensea/src/nosc.c:239:58: error: dereferencing pointer to incomplete type
     int fd = socket(res->ai_family, res->ai_socktype, res->ai_protocol);
                                                          ^
/home/ubuntu/frequensea/src/nosc.c:245:21: error: dereferencing pointer to incomplete type
     if (bind(fd, res->ai_addr, res->ai_addrlen) == -1) {
                     ^
/home/ubuntu/frequensea/src/nosc.c:245:35: error: dereferencing pointer to incomplete type
     if (bind(fd, res->ai_addr, res->ai_addrlen) == -1) {
                                   ^
/home/ubuntu/frequensea/src/nosc.c:250:5: error: implicit declaration of function ‘freeaddrinfo’ [-Werror=implicit-function-declaration]
     freeaddrinfo(res);
     ^
/home/ubuntu/frequensea/src/nosc.c:271:17: error: implicit declaration of function ‘nanosleep’ [-Werror=implicit-function-declaration]
                 nanosleep((struct timespec[]){{0, 1 * MILLIS_TO_NANOS}}, NULL);
                 ^
/home/ubuntu/frequensea/src/nosc.c:226:21: error: unused variable ‘hints’ [-Werror=unused-variable]
     struct addrinfo hints;
                     ^
cc1: all warnings being treated as errors
CMakeFiles/frequensea.dir/build.make:169: recipe for target 'CMakeFiles/frequensea.dir/src/nosc.c.o' failed
make[2]: *** [CMakeFiles/frequensea.dir/src/nosc.c.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/frequensea.dir/all' failed
make[1]: *** [CMakeFiles/frequensea.dir/all] Error 2
Makefile:72: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by fdb** [comment]
The Linux build is currently broken: check issue #2. Sorry for that! I'll try to fix this this week.
